config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: [:index, :new, :create]
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    follower = passive_relationships.find_by(following_id:user.id)
    return follower.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.new(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end
  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowAppRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <h1 class="app-name"><a href="/">FollowApp</a></h1>
      <% if user_signed_in? %>
        <div class="user-mypage">
          <%= link_to "#{current_user.name}のマイページ", user_path(current_user), class: "btn" %>
        </div>
        <%= link_to "ログアウト", destroy_user_session_path,class: "btn", data: { turbo_method: :delete } %>
        <%= link_to  "投稿する", new_tweet_path, class: "btn" %>
      <% end %>
    </header>
      <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <p class = "tweet-text"><%= tweet.text %></p>
  <div class="tweet-name">
    <%= link_to  "投稿者：#{tweet.user.name}", user_path(tweet.user)%>
  </div>
</div>

app/views/tweets/index.html.erb
<div class = "tweets">
  <%= render partial: "tweet", collection: @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="tweet-form">
  <%= form_with(model: @tweet, local: true) do |form| %>
    <h3>投稿する</h3>
    <div class="t-form">
      <%= form.text_area :text, class: "t-text",placeholder: "text" , rows: "10" %>
      <%= form.submit "SEND" ,class:"btn"%>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-paged">
  <div class="user-contentsd">
    <p class="user-named">ユーザー名：<%= @user.name %></p>
    <% if current_user != @user %>
    <% if @user.followed_by?(current_user) %>
      <%=link_to "フォロー中", user_relationships_path(@user.id),class: "btn", data: { turbo_method: :delete } %>
    <% else %>
      <%=link_to "フォローする", user_relationships_path(@user.id),class: "btn", data: { turbo_method: :post } %>
    <% end %>
     <% end %>
     <h3>フォロー</h3>
    <% @user.followings.each do |user| %>
      <p class=“f-user”><%= link_to user.name, user_path(user.id) %></p>
    <% end %>
      <h3>フォロワー</h3>
    <% @user.followers.each do |user| %>
      <p class=“f-user”><%= link_to user.name, user_path(user.id) %></p>
    <% end %>
  </div>
</div>